package assortment_of_things.abyss.hullmods.basic

import assortment_of_things.abyss.hullmods.BaseAlteration
import assortment_of_things.misc.addNegativePara
import assortment_of_things.misc.baseOrModSpec
import com.fs.starfarer.api.Global
import com.fs.starfarer.api.campaign.econ.MarketAPI
import com.fs.starfarer.api.combat.MutableShipStatsAPI
import com.fs.starfarer.api.combat.ShipAPI
import com.fs.starfarer.api.combat.ShipVariantAPI
import com.fs.starfarer.api.fleet.FleetMemberAPI
import com.fs.starfarer.api.impl.campaign.ids.Stats
import com.fs.starfarer.api.impl.combat.PhaseCloakStats
import com.fs.starfarer.api.ui.TooltipMakerAPI
import com.fs.starfarer.api.util.Misc

class PhaseStabiliserHullmod : BaseAlteration() {

    var modID = "rat_phase_stabiliser"

    override fun applyEffectsBeforeShipCreation(hullSize: ShipAPI.HullSize?, stats: MutableShipStatsAPI?, id: String?) {
        super.applyEffectsBeforeShipCreation(hullSize, stats, id)

        stats!!.phaseCloakUpkeepCostBonus.modifyMult(modID, 0.75f)
    }

    override fun advanceInCombat(ship: ShipAPI?, amount: Float) {
        if (Global.getCombatEngine() == null) return
        var level = ship?.phaseCloak?.effectLevel

        if (level == null && ship!!.isPhased) {
            level = 1f
        }
        if (level == null) level = 0f

        var stats = ship!!.mutableStats

        var id = modID + "_" + ship.id

        val shipTimeMult = 1f + (0.5f * level)

        stats.getTimeMult().modifyMult(id, shipTimeMult)
        if (Global.getCombatEngine().playerShip == ship) {
            Global.getCombatEngine().timeMult.modifyMult(id, 1f / shipTimeMult)
        } else {
            Global.getCombatEngine().timeMult.unmodify(id)
        }
    }

    override fun shouldAddDescriptionToTooltip(hullSize: ShipAPI.HullSize?, ship: ShipAPI?, isForModSpec: Boolean): Boolean {
        return false
    }

    override fun addPostDescriptionSection(tooltip: TooltipMakerAPI?, hullSize: ShipAPI.HullSize?, ship: ShipAPI?, width: Float, isForModSpec: Boolean) {

        tooltip!!.addSpacer(5f)
        tooltip!!.addPara("Stabilises the ships phase cloak, increasing the phase timeflow by 50%%. The stabiisation also decreases the flux generated by the cloak by 25%%", 0f
        ,Misc.getTextColor(), Misc.getHighlightColor(), "phase timeflow", "50%", "flux", "25%")

    }

    override fun canInstallAlteration(member: FleetMemberAPI?, variant: ShipVariantAPI?, marketAPI: MarketAPI?): Boolean {
        return member!!.baseOrModSpec().isPhase
    }

    override fun cannotInstallAlterationTooltip(tooltip: TooltipMakerAPI?, member: FleetMemberAPI?, variant: ShipVariantAPI?, width: Float) {
        if (!member!!.baseOrModSpec().isPhase) {
            tooltip!!.addNegativePara("Can only be installed on phaseships")
        }
    }
}